"""replace feature boolean columns with feature_flags jsonb

Revision ID: 142dd274e86f
Revises: b89b8b8fd218
Create Date: 2026-04-19 17:30:16.133587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142dd274e86f'
down_revision: Union[str, None] = 'b89b8b8fd218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('site_settings', 'feature_games')
    op.drop_column('site_settings', 'feature_gallery')
    op.drop_column('site_settings', 'feature_badges')
    op.drop_column('site_settings', 'feature_challenges')
    op.drop_column('site_settings', 'feature_abacus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('feature_abacus', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('site_settings', sa.Column('feature_challenges', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('site_settings', sa.Column('feature_badges', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('site_settings', sa.Column('feature_gallery', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('site_settings', sa.Column('feature_games', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('site_settings', 'feature_flags')
    # ### end Alembic commands ###
