"""add badge and drawing tables

Revision ID: 471dd966fefb
Revises: m3n4o5p6q7r8
Create Date: 2026-04-17 05:39:48.768438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471dd966fefb'
down_revision: Union[str, None] = 'm3n4o5p6q7r8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_bn', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('description_bn', sa.String(length=1000), nullable=True),
    sa.Column('icon_url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_profile_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_profile_id', 'badge_id', name='uq_child_badge')
    )
    op.create_table('drawings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('title_bn', sa.String(length=500), nullable=True),
    sa.Column('challenge_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drawing_id', 'user_id', name='uq_drawing_like')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawing_likes')
    op.drop_table('drawings')
    op.drop_table('child_badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
