"""Add SiteSettings

Revision ID: 871c777729ce
Revises: d4e5f6a7b8c9
Create Date: 2026-04-02 02:26:23.768357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871c777729ce'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('support_phone', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('office_address', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('footer_description_en', sa.Text(), nullable=True),
    sa.Column('footer_description_bn', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_certificates_number', table_name='certificates')
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.drop_index('ix_reviews_course_id', table_name='reviews')
    op.drop_index('ix_reviews_user_course', table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_user_course', 'reviews', ['user_id', 'course_id'], unique=True)
    op.create_index('ix_reviews_course_id', 'reviews', ['course_id'], unique=False)
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.create_index('ix_certificates_number', 'certificates', ['certificate_number'], unique=True)
    op.drop_table('site_settings')
    # ### end Alembic commands ###
