"""add_course_feedback

Revision ID: 8d1ec14064e3
Revises: 653f78263f62
Create Date: 2026-04-11 16:27:48.596851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1ec14064e3'
down_revision: Union[str, None] = '653f78263f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_assignment_submissions_lesson_child', table_name='assignment_submissions')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_index('ix_assignment_submissions_lesson_child', 'assignment_submissions', ['lesson_id', 'child_profile_id'], unique=True)
    op.drop_table('course_feedback')
    # ### end Alembic commands ###
