"""add feature toggles to site settings

Revision ID: b89b8b8fd218
Revises: 9feab46ab4c9
Create Date: 2026-04-19 17:25:02.306149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89b8b8fd218'
down_revision: Union[str, None] = '9feab46ab4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('site_settings', sa.Column('feature_games', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('site_settings', sa.Column('feature_abacus', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('site_settings', sa.Column('feature_badges', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('site_settings', sa.Column('feature_gallery', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('site_settings', sa.Column('feature_challenges', sa.Boolean(), nullable=False, server_default='true'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'feature_challenges')
    op.drop_column('site_settings', 'feature_gallery')
    op.drop_column('site_settings', 'feature_badges')
    op.drop_column('site_settings', 'feature_abacus')
    op.drop_column('site_settings', 'feature_games')
    # ### end Alembic commands ###
