"""add_rating_to_feedback

Revision ID: d6b071fcb617
Revises: 8d1ec14064e3
Create Date: 2026-04-11 16:50:14.643596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b071fcb617'
down_revision: Union[str, None] = '8d1ec14064e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_feedback', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_feedback', 'rating')
    # ### end Alembic commands ###
