"""add fraud_config table and guest order fields

Revision ID: e82b0ff946fd
Revises: 64859b31e2dd
Create Date: 2026-04-12 16:45:14.696430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e82b0ff946fd'
down_revision: Union[str, None] = '64859b31e2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_rate_window_hours', sa.Integer(), nullable=True),
    sa.Column('phone_rate_max_orders', sa.Integer(), nullable=True),
    sa.Column('phone_rate_score', sa.Integer(), nullable=True),
    sa.Column('ip_rate_window_hours', sa.Integer(), nullable=True),
    sa.Column('ip_rate_max_orders', sa.Integer(), nullable=True),
    sa.Column('ip_rate_score', sa.Integer(), nullable=True),
    sa.Column('fingerprint_rate_window_hours', sa.Integer(), nullable=True),
    sa.Column('fingerprint_rate_max_orders', sa.Integer(), nullable=True),
    sa.Column('fingerprint_rate_score', sa.Integer(), nullable=True),
    sa.Column('min_address_length', sa.Integer(), nullable=True),
    sa.Column('address_quality_score', sa.Integer(), nullable=True),
    sa.Column('max_single_item_qty', sa.Integer(), nullable=True),
    sa.Column('max_total_items', sa.Integer(), nullable=True),
    sa.Column('quantity_spike_score', sa.Integer(), nullable=True),
    sa.Column('phone_format_score', sa.Integer(), nullable=True),
    sa.Column('vpn_proxy_score', sa.Integer(), nullable=True),
    sa.Column('blacklist_score', sa.Integer(), nullable=True),
    sa.Column('prepaid_discount_score', sa.Integer(), nullable=True),
    sa.Column('medium_risk_threshold', sa.Integer(), nullable=True),
    sa.Column('high_risk_threshold', sa.Integer(), nullable=True),
    sa.Column('max_cart_value', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        INSERT INTO fraud_config (id) VALUES (1)
        ON CONFLICT (id) DO NOTHING;
    """)
    op.add_column('orders', sa.Column('is_guest', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('fraud_score', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('fraud_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('orders', sa.Column('device_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'device_fingerprint')
    op.drop_column('orders', 'ip_address')
    op.drop_column('orders', 'fraud_flags')
    op.drop_column('orders', 'fraud_score')
    op.drop_column('orders', 'is_guest')
    op.drop_table('fraud_config')
    # ### end Alembic commands ###
