"""add hard block toggles to fraud_config

Revision ID: ea808583fe6f
Revises: e82b0ff946fd
Create Date: 2026-04-12 17:41:44.839516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea808583fe6f'
down_revision: Union[str, None] = 'e82b0ff946fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fraud_config', sa.Column('block_phone_enabled', sa.Boolean(), nullable=True))
    op.add_column('fraud_config', sa.Column('block_ip_enabled', sa.Boolean(), nullable=True))
    op.add_column('fraud_config', sa.Column('block_fingerprint_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fraud_config', 'block_fingerprint_enabled')
    op.drop_column('fraud_config', 'block_ip_enabled')
    op.drop_column('fraud_config', 'block_phone_enabled')
    # ### end Alembic commands ###
